### ISSUE TITLE
Different database

### ISSUE THREAD

**Issue by subdesign** [wuifdesign/laravel-multiauth#1]
Can I use multiauth using different databases ? For example I have a **users** table in the current project database, but have to use a different database and table for the 2nd auth. Btw the 2nd **users** table is also a Laravel project, so structure is the same.

What is the difference between sboo/multiauth and your project ?

Thanks

**Comment by wuifdesign** [comment]
You should be able to use 2 or more databases. If you use Eloquent you can just add the connection name of the second databe to the model

```
<?php
class User extends Eloquent {
    protected $connection = 'connection_name';
}
```

The difference between my project and _sboo/multiauth_ is, that my project should work fine with the default AuthController provided with Laravel 5.1 because it overrides the default Auth class. (_sboo/multiauth_ currently dosn't support this for lavavel 5.1)

I hope this helps.

**Comment by subdesign** [comment]
Nice, thank you.
