### ISSUE TITLE
usage without facade

### ISSUE THREAD

**Issue by subdesign** [wuifdesign/laravel-multiauth#11]
Can I use Auth without facade with your package? I've put a part of my code into a queue, but with that I get "trying to get property of non object" error on **Auth::type('user')->driver()->user()->id** line.
Not using a queue, Auth facade works well.

I tried to use a contract, injected into the constructor, but i get "Call to undefined method WuifDesign\MultiAuth\Guard::type() " error.

EDIT: eg. **\Auth::currentType()** works, only the above line doesn't work. Hmm..

EDIT 2: in a plain controller, /wo queue job, I can get the user model easily:
\Auth::type('user')->user();
Maybe I cant reach the session in a queue?

**Comment by wuifdesign** [comment]
why are you using the "driver" in Auth::type('user')->driver()->user()->id?

**Comment by subdesign** [comment]
Because Auth::type('user')->id; gives the following error exception:

```
Undefined property: WuifDesign\MultiAuth\AuthManager::$id
```

But above mentioned line gives the read ID back.

**Comment by wuifdesign** [comment]
Sorry, but i think i don't get what you want to do. If you want the user inside a queue you should add it to the constructor and parse it as a variable to the queue (like they do it in the example: http://laravel.com/docs/master/queues#writing-job-classes).
Otherwise the queue can't know wich user it should take. Or do i miss something?

**Comment by subdesign** [comment]
thx for the job constructor solution.
